var keys = {
    Escape: { mainLabel: "Esc", secLabel: "", bottomLabel: "", className: "key Esc controlKey Escape", rowNum: 1 },
    Digit1: { mainLabel: "1", secLabel: "!", bottomLabel: "F1", className: "key one Digit1", rowNum: 1 },
    Digit2: { mainLabel: "2", secLabel: "@", bottomLabel: "F2", className: "key two Digit2", rowNum: 1 },
    Digit3: { mainLabel: "3", secLabel: "#", bottomLabel: "F3", className: "key three Digit3", rowNum: 1 },
    Digit4: { mainLabel: "4", secLabel: "$", bottomLabel: "F4", className: "key four Digit4", rowNum: 1 },
    Digit5: { mainLabel: "5", secLabel: "%", bottomLabel: "F5", className: "key five Digit5", rowNum: 1 },
    Digit6: { mainLabel: "6", secLabel: "^", bottomLabel: "F6", className: "key six Digit6", rowNum: 1 },
    Digit7: { mainLabel: "7", secLabel: "&", bottomLabel: "F7", className: "key seven Digit7", rowNum: 1 },
    Digit8: { mainLabel: "8", secLabel: "*", bottomLabel: "F8", className: "key eight Digit8", rowNum: 1 },
    Digit9: { mainLabel: "9", secLabel: "(", bottomLabel: "F9", className: "key nine Digit9", rowNum: 1 },
    Digit0: { mainLabel: "0", secLabel: ")", bottomLabel: "F10", className: "key zero Digit0", rowNum: 1 },
    Minus: { mainLabel: "-", secLabel: "_", bottomLabel: "F11", className: "key minus Minus", rowNum: 1 },
    Equal: { mainLabel: "=", secLabel: "+", bottomLabel: "F12", className: "key equal Equal", rowNum: 1 },
    Backspace: { mainLabel: "Backspace", secLabel: "", bottomLabel: "", className: "key backspace controlKey Backspace", rowNum: 1 },

    Tab: { mainLabel: "Tab", secLabel: "", bottomLabel: "", className: "key tab controlKey Tab", rowNum: 2 },
    KeyQ: { mainLabel: "Q", secLabel: "", bottomLabel: "", className: "key Q KeyQ", rowNum: 2 },
    KeyW: { mainLabel: "W", secLabel: "", bottomLabel: "", className: "key W KeyW", rowNum: 2 },
    KeyE: { mainLabel: "E", secLabel: "", bottomLabel: "", className: "key E KeyE", rowNum: 2 },
    KeyR: { mainLabel: "R", secLabel: "", bottomLabel: "", className: "key R KeyR", rowNum: 2 },
    KeyT: { mainLabel: "T", secLabel: "", bottomLabel: "", className: "key T KeyT", rowNum: 2 },
    KeyY: { mainLabel: "Y", secLabel: "", bottomLabel: "PrtSc", className: "key Y KeyY", rowNum: 2 },
    KeyU: { mainLabel: "U", secLabel: "", bottomLabel: "ScrLk", className: "key U KeyU", rowNum: 2 },
    KeyI: { mainLabel: "I", secLabel: "", bottomLabel: "Pause", className: "key I KeyI", rowNum: 2 },
    KeyO: { mainLabel: "O", secLabel: "", bottomLabel: "", className: "key O KeyO", rowNum: 2 },
    KeyP: { mainLabel: "P", secLabel: "", bottomLabel: "", className: "key P KeyP", rowNum: 2 },
    BracketLeft: { mainLabel: "[", secLabel: "{", bottomLabel: "", className: "key leftBracket BracketLeft", rowNum: 2 },
    BracketRight: { mainLabel: "]", secLabel: "}", bottomLabel: "", className: "key rightBracket BracketRight", rowNum: 2 },
    Backslash: { mainLabel: "\\", secLabel: "|", bottomLabel: "", className: "key backslash Backslash", rowNum: 2 },

    CapsLock: { mainLabel: "CapsLock", secLabel: "", bottomLabel: "", className: "key capslock controlKey CapsLock", rowNum: 3 },
    KeyA: { mainLabel: "A", secLabel: "", bottomLabel: "", className: "key A KeyA", rowNum: 3 },
    KeyS: { mainLabel: "S", secLabel: "", bottomLabel: "", className: "key S KeyS", rowNum: 3 },
    KeyD: { mainLabel: "D", secLabel: "", bottomLabel: "", className: "key D KeyD", rowNum: 3 },
    KeyF: { mainLabel: "F", secLabel: "", bottomLabel: "", className: "key F KeyF", rowNum: 3 },
    KeyG: { mainLabel: "G", secLabel: "", bottomLabel: "", className: "key G KeyG", rowNum: 3 },
    KeyH: { mainLabel: "H", secLabel: "", bottomLabel: "Insert", className: "key H KeyH", rowNum: 3 },
    KeyJ: { mainLabel: "J", secLabel: "", bottomLabel: "Home", className: "key J KeyJ", rowNum: 3 },
    KeyK: { mainLabel: "K", secLabel: "", bottomLabel: "PgUp", className: "key K KeyK", rowNum: 3 },
    KeyL: { mainLabel: "L", secLabel: "", bottomLabel: "", className: "key L KeyKeyL", rowNum: 3 },
    Semicolon: { mainLabel: ";", secLabel: ":", bottomLabel: "", className: "key semicolon Semicolon", rowNum: 3 },
    Quote: { mainLabel: "'", secLabel: "\"", bottomLabel: "", className: "key quote Quote", rowNum: 3 },
    Enter: { mainLabel: "Enter", secLabel: "", bottomLabel: "", className: "key enter controlKey Enter", rowNum: 3 },

    ShiftLeft: { mainLabel: "Shift", secLabel: "", bottomLabel: "", className: "key leftShift controlKey ShiftLeft", rowNum: 4 },
    KeyZ: { mainLabel: "Z", secLabel: "", bottomLabel: "", className: "key Z KeyZ", rowNum: 4 },
    KeyX: { mainLabel: "X", secLabel: "", bottomLabel: "", className: "key X KeyX", rowNum: 4 },
    KeyC: { mainLabel: "C", secLabel: "", bottomLabel: "", className: "key C KeyC", rowNum: 4 },
    KeyV: { mainLabel: "V", secLabel: "", bottomLabel: "", className: "key V KeyV", rowNum: 4 },
    KeyB: { mainLabel: "B", secLabel: "", bottomLabel: "", className: "key B KeyB", rowNum: 4 },
    KeyN: { mainLabel: "N", secLabel: "", bottomLabel: "Del", className: "key N KeyN", rowNum: 4 },
    KeyM: { mainLabel: "M", secLabel: "", bottomLabel: "End", className: "key M KeyM", rowNum: 4 },
    Comma: { mainLabel: ",", secLabel: "<", bottomLabel: "PgDn", className: "key comma Comma", rowNum: 4 },
    Period: { mainLabel: ".", secLabel: ">", bottomLabel: "", className: "key period Period", rowNum: 4 },
    Slash: { mainLabel: "/", secLabel: "?", bottomLabel: "↑", className: "key slash Slash ArrowUp", rowNum: 4 },
    ShiftRight: { mainLabel: "Shift", secLabel: "", bottomLabel: "", className: "key rightShift controlKey ShiftRight", rowNum: 4 },

    ControlLeft: { mainLabel: "Ctrl", secLabel: "", bottomLabel: "", className: "key leftCtrl controlKey ControlLeft", rowNum: 5 },
    MetaLeft: { mainLabel: "Win", secLabel: "", bottomLabel: "", className: "key leftWin controlKey MetaLeft", rowNum: 5 },
    AltLeft: { mainLabel: "Alt", secLabel: "", bottomLabel: "", className: "key leftAlt controlKey AltLeft", rowNum: 5 },
    Space: { mainLabel: " ", secLabel: "", bottomLabel: "", className: "key spacebar Space", rowNum: 5 },
    AltRight: { mainLabel: "Alt", secLabel: "", bottomLabel: "←", className: "key rightAlt ArrowLeft controlKey AltRight", rowNum: 5 },
    PrintScreen: { mainLabel: "Prt", secLabel: "", bottomLabel: "↓", className: "key prt ArrowDown controlKey PrintScreen", rowNum: 5 },
    ControlRight: { mainLabel: "Ctrl", secLabel: "", bottomLabel: "→", className: "key rightCtrl ArrowRight controlKey ControlRight", rowNum: 5 },
    Zan: { mainLabel: "ZAN", secLabel: "", bottomLabel: "⌨️", className: "key zan controlKey Zan", rowNum: 5 }
};