var keys = {
    Escape: { value: "Esc", secLabel: "", bottomLabel: "", className: "key Esc Escape controlKey", rowNum: 1 },
    Digit1: { value: "1", secLabel: "!", bottomLabel: "F1", className: "key one Digit1", rowNum: 1 },
    Digit2: { value: "2", secLabel: "@", bottomLabel: "F2", className: "key two Digit2", rowNum: 1 },
    Digit3: { value: "3", secLabel: "#", bottomLabel: "F3", className: "key three Digit3", rowNum: 1 },
    Digit4: { value: "4", secLabel: "$", bottomLabel: "F4", className: "key four Digit4", rowNum: 1 },
    Digit5: { value: "5", secLabel: "%", bottomLabel: "F5", className: "key five Digit5", rowNum: 1 },
    Digit6: { value: "6", secLabel: "^", bottomLabel: "F6", className: "key six Digit6", rowNum: 1 },
    Digit7: { value: "7", secLabel: "&", bottomLabel: "F7", className: "key seven Digit7", rowNum: 1 },
    Digit8: { value: "8", secLabel: "*", bottomLabel: "F8", className: "key eight Digit8", rowNum: 1 },
    Digit9: { value: "9", secLabel: "(", bottomLabel: "F9", className: "key nine Digit9", rowNum: 1 },
    Digit0: { value: "0", secLabel: ")", bottomLabel: "F10", className: "key zero Digit0", rowNum: 1 },
    Minus: { value: "-", secLabel: "_", bottomLabel: "F11", className: "key minus Minus", rowNum: 1 },
    Equal: { value: "=", secLabel: "+", bottomLabel: "F12", className: "key equal Equal", rowNum: 1 },
    Backspace: { value: "Backspace", secLabel: "", bottomLabel: "", className: "key backspace Backspace controlKey", rowNum: 1 },

    Tab: { value: "Tab", secLabel: "", bottomLabel: "", className: "key tab Tab controlKey", rowNum: 2 },
    KeyQ: { value: "Q", secLabel: "", bottomLabel: "", className: "key Q KeyQ", rowNum: 2 },
    KeyW: { value: "W", secLabel: "", bottomLabel: "", className: "key W KeyW", rowNum: 2 },
    KeyE: { value: "E", secLabel: "", bottomLabel: "", className: "key E KeyE", rowNum: 2 },
    KeyR: { value: "R", secLabel: "", bottomLabel: "", className: "key R KeyR", rowNum: 2 },
    KeyT: { value: "T", secLabel: "", bottomLabel: "", className: "key T KeyT", rowNum: 2 },
    KeyY: { value: "Y", secLabel: "", bottomLabel: "PrtSc", className: "key Y KeyY", rowNum: 2 },
    KeyU: { value: "U", secLabel: "", bottomLabel: "ScrLk", className: "key U KeyU", rowNum: 2 },
    KeyI: { value: "I", secLabel: "", bottomLabel: "Pause", className: "key I KeyI", rowNum: 2 },
    KeyO: { value: "O", secLabel: "", bottomLabel: "", className: "key O KeyO", rowNum: 2 },
    KeyP: { value: "P", secLabel: "", bottomLabel: "", className: "key P KeyP", rowNum: 2 },
    BracketLeft: { value: "[", secLabel: "{", bottomLabel: "", className: "key leftBracket BracketLeft", rowNum: 2 },
    BracketRight: { value: "]", secLabel: "}", bottomLabel: "", className: "key rightBracket BracketRight", rowNum: 2 },
    Backslash: { value: "\\", secLabel: "|", bottomLabel: "", className: "key backslash Backslash", rowNum: 2 },

    CapsLock: { value: "CapsLock", secLabel: "", bottomLabel: "", className: "key capslock CapsLock controlKey", rowNum: 3 },
    KeyA: { value: "A", secLabel: "", bottomLabel: "", className: "key A KeyA", rowNum: 3 },
    KeyS: { value: "S", secLabel: "", bottomLabel: "", className: "key S KeyS", rowNum: 3 },
    KeyD: { value: "D", secLabel: "", bottomLabel: "", className: "key D KeyD", rowNum: 3 },
    KeyF: { value: "F", secLabel: "", bottomLabel: "", className: "key F KeyF", rowNum: 3 },
    KeyG: { value: "G", secLabel: "", bottomLabel: "", className: "key G KeyG", rowNum: 3 },
    KeyH: { value: "H", secLabel: "", bottomLabel: "Insert", className: "key H KeyH", rowNum: 3 },
    KeyJ: { value: "J", secLabel: "", bottomLabel: "Home", className: "key J KeyJ", rowNum: 3 },
    KeyK: { value: "K", secLabel: "", bottomLabel: "PgUp", className: "key K KeyK", rowNum: 3 },
    KeyL: { value: "L", secLabel: "", bottomLabel: "", className: "key L KeyKeyL", rowNum: 3 },
    Semicolon: { value: ";", secLabel: ":", bottomLabel: "", className: "key semicolon Semicolon", rowNum: 3 },
    Quote: { value: "'", secLabel: "\"", bottomLabel: "", className: "key quote Quote", rowNum: 3 },
    Enter: { value: "Enter", secLabel: "", bottomLabel: "", className: "key enter Enter controlKey", rowNum: 3 },

    ShiftLeft: { value: "Shift", secLabel: "", bottomLabel: "", className: "key leftShift ShiftLeft controlKey", rowNum: 4 },
    KeyZ: { value: "Z", secLabel: "", bottomLabel: "", className: "key Z KeyZ", rowNum: 4 },
    KeyX: { value: "X", secLabel: "", bottomLabel: "", className: "key X KeyX", rowNum: 4 },
    KeyC: { value: "C", secLabel: "", bottomLabel: "", className: "key C KeyC", rowNum: 4 },
    KeyV: { value: "V", secLabel: "", bottomLabel: "", className: "key V KeyV", rowNum: 4 },
    KeyB: { value: "B", secLabel: "", bottomLabel: "", className: "key B KeyB", rowNum: 4 },
    KeyN: { value: "N", secLabel: "", bottomLabel: "Del", className: "key N KeyN", rowNum: 4 },
    KeyM: { value: "M", secLabel: "", bottomLabel: "End", className: "key M KeyM", rowNum: 4 },
    Comma: { value: ",", secLabel: "<", bottomLabel: "PgDn", className: "key comma Comma", rowNum: 4 },
    Period: { value: ".", secLabel: ">", bottomLabel: "", className: "key period Period", rowNum: 4 },
    Slash: { value: "/", secLabel: "?", bottomLabel: "↑", className: "key slash Slash ArrowUp", rowNum: 4 },
    ShiftRight: { value: "Shift", secLabel: "", bottomLabel: "", className: "key rightShift ShiftRight controlKey", rowNum: 4 },

    ControlLeft: { value: "Ctrl", secLabel: "", bottomLabel: "", className: "key leftCtrl ControlLeft controlKey", rowNum: 5 },
    MetaLeft: { value: "Win", secLabel: "", bottomLabel: "", className: "key leftWin MetaLeft controlKey", rowNum: 5 },
    AltLeft: { value: "Alt", secLabel: "", bottomLabel: "", className: "key leftAlt AltLeft controlKey", rowNum: 5 },
    Space: { value: " ", secLabel: "", bottomLabel: "", className: "key spacebar Space", rowNum: 5 },
    AltRight: { value: "Alt", secLabel: "", bottomLabel: "←", className: "key rightAlt ArrowLeft AltRight controlKey", rowNum: 5 },
    PrintScreen: { value: "Prt", secLabel: "", bottomLabel: "↓", className: "key prt ArrowDown PrintScreen controlKey", rowNum: 5 },
    ControlRight: { value: "Ctrl", secLabel: "", bottomLabel: "→", className: "key rightCtrl ArrowRight ControlRight controlKey", rowNum: 5 },
    Zan: { value: "ZAN", secLabel: "", bottomLabel: "⌨️", className: "key zan Zan controlKey", rowNum: 5 }
};